<?php

class Che_Techtalk_Block_Adminhtml_Contact_Form extends Mage_Adminhtml_Block_Widget_Form
{
//    public function __construct(array $args)
//    {
//        parent::__construct($args);
//    }
//    protected function _prepareLayout()
//    {
//        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
//    }
//    protected function _prepareForm()
//    {
//        return parent::_prepareForm(); // TODO: Change the autogenerated stub
//    }

}
