<?php


class Che_Techtalk_Block_Adminhtml_Contact_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
//    public function __construct()
//    {
//
//
//    }
//    protected function _prepareCollection()
//    {
//        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
//    }
//    protected function _prepareColumns()
//    {
//        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
//    }
//    public function getRowUrl($row)
//    {
//
//    }
//    public function getGridUrl($params=[])
//    {
//        return parent::getGridUrl(); // TODO: Change the autogenerated stub
//    }


}