<?php

/**
 *  @var Che_Techtalk_Block_View $this
**/

?>
<ul>
    <li><?php echo $this->getRequestRecord()->getName() . " said:"; ?></li>
    <li><?=$this->getRequestRecord()->getComment()?></li>


</ul><br />
<h1>OTHER COMMENTS: </h1>
<ul>
    <?php foreach ($this->getCollection() as $val) { ?>
        <li><?php echo $val->getName()." said:" ?> </li>
        <li><?= $val->getComment() ?></li><br />
    <?php } ?>
</ul>
